---
title: "working_along_ch4"
author: "Warren Kretzschmar"
date: "6/16/2021"
output: html_document
---
```{r}
curve( exp( -x^2 ) , from=-3 , to=3 )
```

```{r}
library(ggplot2)
library(tidyverse)
library(rethinking)
data(Howell1)
d = Howell1
```
```{r}
d2 = d[d$age >= 18,]
d2
```

```{r}
plot( d2$height ~ d2$weight )
```

```{r}
# y = a + b(x_i - x_bar)
set.seed(2971)
N <- 100
a <- rnorm( N , 178 , 20 ) 
b <- rnorm( N , 0 , 10 )
a

xbar = d2$weight %>% mean
params = tibble(a=a,b=b) %>% 
  mutate(a1 = a - b*xbar)
ggplot(params) + geom_abline(aes(slope=b, intercept=a1)) +
  xlim(30,60) + ylim(-100,400)
```
```{r}
b <- rlnorm( 1e4 , 0 , 1 )
dens(b, xlim=c(0,5) , adj=0.1)
```

```{r}
# y = a + b(x_i - x_bar)
set.seed(2971)
N <- 100
a <- rnorm( N , 178 , 20 ) 
b <- rlnorm( N , 0 , 1)

xbar = d2$weight %>% mean
params = tibble(a=a,b=b) %>% 
  mutate(a1 = a - b*xbar)
ggplot(params) + geom_abline(aes(slope=b, intercept=a1)) +
  xlim(30,60) + ylim(-100,400)
```
```{r}
xbar = mean(d2$weight)
m4.3 = quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b*(weight - xbar),
    a ~ dnorm(178, 20),
    b ~ dlnorm(0, 1),
    sigma ~ dunif(0,50)
  ),
  data=d2
)
```

```{r}
precis(m4.3)
plot( height ~ weight , data=d2 , col=rangi2 )
post <- extract.samples( m4.3 )
a_map <- mean(post$a)
b_map <- mean(post$b)
curve( a_map + b_map*(x - xbar) , add=TRUE )
```
```{r}
N <- 200
dN <- d2[ 1:N , ] 
mN <- quap(
  alist(
    height ~ dnorm( mu , sigma ) ,
  mu <- a + b*( weight - mean(weight) ) ,
  a ~ dnorm( 178 , 20 ) ,
  b ~ dlnorm( 0 , 1 ) ,
  sigma ~ dunif( 0 , 50 )
) , 
data=dN )

post <- extract.samples( mN , n=20 )
plot( dN$weight , dN$height ,
    xlim=range(d2$weight) , ylim=range(d2$height) ,
    col=rangi2 , xlab="weight" , ylab="height" )
mtext(concat("N = ",N))
# plot the lines, with transparency
for ( i in 1:20 ) curve( 
  post$a[i] + post$b[i]*(x-mean(dN$weight)) ,
  col=col.alpha("black",0.3) ,
  add=TRUE 
  )
```

```{r}
plot(d$weight, d$height)
```
```{r}
d$weight_s = (d$weight - mean(d$weight))/sd(d$weight)
d$weight_s2 = d$weight_s^2

m4.5 <- quap(
  alist(
    height ~ dnorm( mu , sigma ) ,
  mu <- a + b1* weight_s + b2*weight_s2 ,
  a ~ dnorm( 178 , 20 ) ,
  b1 ~ dlnorm( 0 , 1 ) ,
  b2 ~ dnorm(0,1),
  sigma ~ dunif( 0 , 50 )
) , 
data=d )
precis(m4.5)
```
```{r}
weight.seq <- seq( from=-2.2 , to=2 , length.out=30 )
pred_dat <- list( weight_s=weight.seq , weight_s2=weight.seq^2 )
mu <- link( m4.5 , data=pred_dat )
mu.mean <- apply( mu , 2 , mean )
mu.PI <- apply( mu , 2 , PI , prob=0.89 )
sim.height <- sim( m4.5 , data=pred_dat )
height.PI <- apply( sim.height , 2 , PI , prob=0.89 )
```
```{r}
plot( height ~ weight_s , d , col=col.alpha(rangi2,0.5) )
lines( weight.seq , mu.mean )
shade( mu.PI , weight.seq )
shade( height.PI , weight.seq )
```

```{r}
# 4.72
data(cherry_blossoms)
d = cherry_blossoms
precis(d)
plot(d$year, d$temp)
```
```{r}
d2 <- d[ complete.cases(d$temp) , ] # complete cases on temp
num_knots <- 15
knot_list <- quantile( d2$year , probs=seq(0,1,length.out=num_knots) )
library(splines)
B <- bs(d2$year,
        knots=knot_list[-c(1,num_knots)] ,
        degree=3 , 
        intercept=TRUE )
B
```

