---
title: "Chapter 4 exercises"
author: "Warren Kretzschmar"
date: "6/19/2021"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(rethinking)
```

```{r}
# 4M1
mu = rnorm(1e4, 0, 10)
sigma = rexp(1e4, 1)
precis(mu)
precis(sigma)
hist(rnorm(1e4, mean=mu, sd=sigma))
x = seq(from=0.1, to=10, by=0.1)
plot(x, dexp(x))
lines(x, exp(x))
```
```{r}
# 4M2
# m4m2 = quap(
#   alist(
#     y ~ dnorm(mu, sigma),
#     mu ~ dnorm(0, 10),
#     sigma ~ dexp(1)
#   )
# )
```

### 4M3
```
y_i ~ Normal( mu, sigma)
mu_i = a + b*x_i
a ~ Normal(0, 1)
b ~ Uniform(0, 1)
sigma ~ Exponential(1)
```

### 4M4
```
y_i ~ Normal(mu_i, sigma)
mu_i = a + b*(x_i - xbar)
a ~ Log-Normal(log(1m), log(0.3m))
b ~ Normal(10cm/year, 10 cm/year)
sigma ~ Exponential(10cm)
```

### 4M5
```
# yes:
a ~ Log-Normal(log(0.8m), log(0.3m))
b ~ Log-Normal(log(10cm/year), log(10 cm/year))
```

### 4M6
Yes:
```
sigma ~ Exponential(5cm)
```

### 4H1

```{r}
library(rethinking)
data(Howell1)

d <- Howell1
d2 <- d[ d$age >= 18 , ]
plot(d2$weight, d2$height)
d2$weight_s = (d2$weight - mean(d2$weight))/sd(d2$weight)
plot(d2$weight_s, d2$height)
```
```{r}
m4h1 = quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * weight_s,
    a ~ dlnorm(log(160), log(30)),
    b ~ dnorm(3, 1),
    sigma ~ dunif(0, 50)
  ),
  data=d2
)
precis(m4h1)
```


```{r}
xbar = mean(d2$weight)
new_d = tibble(weight = c(46.95,
                          43.72,
                          64.78,
                          32.59,
                          54.63)) %>% 
  mutate(weight_s = (weight - xbar)/sd(d2$weight))
new_d
preds = sim(m4h1, new_d)
preds %>% dim
new_d = new_d %>% 
  add_column(exp_height = apply(preds, 2, mean)) %>% 
  bind_cols(as.data.frame(apply(preds,2,PI) %>% t))
new_d
# get MAP line
post = extract.samples(m4h1)
a_map = mean(post$a)
b_map = mean(post$b)
b_map
plot(d2$weight, d2$height)
points(new_d$weight, new_d$exp_height, col="red")
curve( a_map + b_map*(x-xbar)/sd(d2$weight), add=TRUE )
points(new_d$weight, new_d$`5%`, col="blue", pch="-", cex=2)
points(new_d$weight, new_d$`94%`, col="blue", pch="-", cex=2)

```

# 4H2

```{r}
d3 = d[d$age < 18,]
d3$weight_s = (d3$weight - mean(d3$weight))/sd(d3$weight)
d3 %>% head
# a
m4h2a = quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * weight_s,
    a ~ dlnorm(log(120), log(30)),
    b ~ dnorm(10, 7), # Made this prior to narrow at first!
    sigma ~ dunif(0,50)
  ),
  data=d3,
  start=list(a=100, b=10, sigma=3)
)
precis(m4h2a)
?quap
post = extract.samples(m4h2a)
a_map = mean(post$a)
b_map = mean(post$b)
b_map
a_map
b_map
(b_map  / sd(d3$weight))
b_map
plot(d3$weight_s, d3$height)
abline(a=a_map, b=b_map)
b_map/sd(d$weight)
```

### 4H2b

Plot the raw data, with height on the vertical axis and weight on the horizontal axis. Super- impose the MAP regression line and 89% interval for the mean. Also superimpose the 89% interval for predicted heights.

```{r}
# 4H2b
xbar = mean(d3$weight)
plot(d3$weight, d3$height)
weight.seq = seq(from=min(d3$weight) , 
      to=max(d3$weight) ,
      by=1)
weight_s.seq = (weight.seq - xbar)/sd(d3$weight)
lines(weight.seq,
      a_map + b_map* weight_s.seq)
mu = link(m4h2a, data=data.frame(weight_s = weight_s.seq))
mu.PI = apply(mu, 2, PI)
shade(mu.PI, weight.seq)

pred.PI = sim(m4h2a, data=data.frame(weight_s=weight_s.seq)) %>% 
  apply(2, PI, prob=0.89)
shade(pred.PI, weight.seq)
# curve( a_map + b_map * (x-xbar)/sd(d3$weight),
#       from=min(d3$weight) , 
#       to=max(d3$weight) ,
#       add=TRUE , 
#       col=col.alpha("black",0.2) )
```

```{r}
# M4H3
plot( height ~ log(weight) , data=d , col=col.alpha(rangi2,0.4) )

m4h3 = quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * log(weight),
    a ~ dnorm(178, 20),
    b ~ dlnorm(0, 1), 
    sigma ~ dunif(0,50)
  ),
  data=d)
precis(m4h3)
```
```{r}
# M4H3b
plot( height ~ weight , data=d , col=col.alpha(rangi2,0.4) )
weight.seq = seq(from=min(d$weight), to=max(d$weight), by=1)

mu = link(m4h3, data = list(weight=weight.seq))
mu.mode = mu %>% apply(2, chainmode)
lines(weight.seq, mu.mode)

mu.PI = mu %>% apply(2, PI, prob=0.97)
shade(mu.PI, weight.seq)

pred = sim(m4h3, data=list(weight=weight.seq))
pred.PI = pred %>% apply(2, PI, prob=0.97)
shade(pred.PI, weight.seq)
```

### M4H4

```{r}
# m4h4 = quap(
#   alist(
#     height ~ dnorm(mu, sigma),
#     mu <- a + b1 * weight_s + b2 * weight_s^2,
#     a ~ dlnorm(log(120), log(30)),
#     b1 ~ dlnorm(0, 1), # Made this prior to narrow at first!
#     b2 ~ dnorm(0, 20), # Made this prior to narrow at first!
#     sigma ~ dunif(0,50)
#   ),
#   data=d3,
#   start=list(a=100, b=10, sigma=3)
# )
set.seed(42)
n_samp = 2e2
s = tibble(
  a = rlnorm(n_samp, log(120), 0.3),
  b1 = rlnorm(n_samp, 1, 1),
  b2 = rnorm(n_samp, -0.01, 0.02)
) 

plot(NULL, xlim=range(d$weight), ylim=c(-100, 300),
     xlab="weight" , ylab="height" )
xbar = mean(d$weight)
for ( i in 1:n_samp ) curve( 
  s$a[i] + s$b1[i]*(x - xbar) + s$b2[i] * (x-xbar)^2 ,
  from=min(d$weight) , 
  to=max(d$weight) ,
  add=TRUE , 
  col=col.alpha("black",0.2) )

```

